Make sure to process version first

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -101,7 +101,7 @@ jobs:
       - name: Set up QEMU
         uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130 # v3.7.0
 
-      - name: Set up Docker Buildx
+      - name: Set up 1.2.0 Buildx
         uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
 
       - name: Log in to Docker Hub
@@ -163,6 +163,16 @@ jobs:
           done
           echo "Tag ${TAG} not visible after waiting"; exit 1
         shell: bash
+
+      - name: Update version in main.go
+        run: |
+            TAG=${{ env.TAG }}
+            if [ -f main.go ]; then
+            sed -i 's/version_replaceme/'"$TAG"'/' main.go
+            echo "Updated main.go with version $TAG"
+            else
+            echo "main.go not found"
+            fi
 
       - name: Ensure repository is at the tagged commit (dispatch only)
         if: ${{ github.event_name == 'workflow_dispatch' }}
@@ -576,28 +586,28 @@ jobs:
       #     sarif_file: trivy-ghcr.sarif
       #     category: Image Vulnerability Scan
 
-      - name: Build binaries
-        env:
-          CGO_ENABLED: "0"
-          GOFLAGS: "-trimpath"
-        run: |
-          set -euo pipefail
-          TAG_VAR="${TAG}"
-          make go-build-release tag=$TAG_VAR
-        shell: bash
+      # - name: Build binaries
+      #   env:
+      #     CGO_ENABLED: "0"
+      #     GOFLAGS: "-trimpath"
+      #   run: |
+      #     set -euo pipefail
+      #     TAG_VAR="${TAG}"
+      #     make go-build-release tag=$TAG_VAR
+      #   shell: bash
 
-      - name: Create GitHub Release
-        uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2.4.2
-        with:
-          tag_name: ${{ env.TAG }}
-          generate_release_notes: true
-          prerelease: ${{ env.IS_RC == 'true' }}
-          files: |
-            bin/*
-          fail_on_unmatched_files: true
-          draft: true
-          body: |
-            ## Container Images
-            - GHCR: `${{ env.GHCR_REF }}`
-            - Docker Hub: `${{ env.DH_REF || 'N/A' }}`
-            **Digest:** `${{ steps.build.outputs.digest }}`
+      # - name: Create GitHub Release
+      #   uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2.4.2
+      #   with:
+      #     tag_name: ${{ env.TAG }}
+      #     generate_release_notes: true
+      #     prerelease: ${{ env.IS_RC == 'true' }}
+      #     files: |
+      #       bin/*
+      #     fail_on_unmatched_files: true
+      #     draft: true
+      #     body: |
+      #       ## Container Images
+      #       - GHCR: `${{ env.GHCR_REF }}`
+      #       - Docker Hub: `${{ env.DH_REF || 'N/A' }}`
+      #       **Digest:** `${{ steps.build.outputs.digest }}`
